#!/bin/bash

# App Store Submission Checklist for PCS Express

echo "📋 PCS EXPRESS - APP STORE SUBMISSION CHECKLIST"
echo "==============================================="
echo ""
echo "Follow these steps to submit your app to the Apple App Store"
echo ""

# Check prerequisites
echo "✓ PREREQUISITES"
echo "  [ ] Apple Developer Account ($99/year) - https://developer.apple.com/account"
echo "  [ ] macOS 12+ with Xcode 15+ installed"
echo "  [ ] App Store Connect access - https://appstoreconnect.apple.com"
echo ""

echo "✓ STEP 1: APP STORE CONNECT SETUP"
echo "  [ ] Go to https://appstoreconnect.apple.com"
echo "  [ ] Click 'My Apps' → '+' → 'New App'"
echo "  [ ] Platform: iOS"
echo "  [ ] Name: PCS Express"
echo "  [ ] Bundle ID: com.pcsexpress.app"
echo "  [ ] SKU: pcsexpress-v1"
echo ""

echo "✓ STEP 2: APP INFORMATION"
echo "  [ ] Category: Lifestyle or Reference"
echo "  [ ] Description: AI-powered PCS guidance for military service members"
echo "  [ ] Keywords: military, PCS, relocation, AI"
echo "  [ ] Privacy Policy URL: https://yoursite.com/privacy"
echo "     (Create a privacy policy if you don't have one)"
echo "  [ ] Support URL: https://yoursite.com/support"
echo ""

echo "✓ STEP 3: PREPARE SCREENSHOTS"
echo "  [ ] Create 2-5 screenshots (iPhone 15 Pro Max: 1242x2208)"
echo "     Tip: Use iOS Simulator (Cmd+S to screenshot)"
echo "  [ ] Show key app features"
echo "  [ ] Add captions if helpful"
echo ""

echo "✓ STEP 4: SIGN IN WITH XCODE"
echo "  1. Open Xcode:"
echo "     open ios/App/App.xcworkspace"
echo "  2. Click 'App' target"
echo "  3. General tab → Account field → Sign In"
echo "  4. Enter your Apple ID"
echo "  5. Create signing certificate (if prompted)"
echo "  [ ] Signing complete"
echo ""

echo "✓ STEP 5: TEST IN SIMULATOR"
echo "  1. In Xcode:"
echo "     Product → Destination → iPhone 15 Pro Max"
echo "     Product → Run (⌘R)"
echo "  2. Test basic functionality:"
echo "     [ ] App launches without crashing"
echo "     [ ] UI renders correctly"
echo "     [ ] Can scroll and interact"
echo "  3. Stop simulator (⌘.)"
echo ""

echo "✓ STEP 6: CREATE ARCHIVE"
echo "  1. In Xcode:"
echo "     Product → Scheme → App"
echo "     Product → Destination → Generic iOS Device"
echo "     Product → Archive (⌘⇧B)"
echo "  2. Wait for 'Archive Succeeded'"
echo "  [ ] Archive created"
echo ""

echo "✓ STEP 7: UPLOAD TO APP STORE"
echo "  1. In Xcode:"
echo "     Window → Organizer"
echo "  2. Select the archive you just created"
echo "  3. Click 'Distribute App'"
echo "  4. Choose 'App Store Connect'"
echo "  5. Follow prompts:"
echo "     - Select Team"
echo "     - Automatic Signing ✓"
echo "     - Upload"
echo "  6. Wait for 'Upload Successful'"
echo "  [ ] Build uploaded"
echo ""

echo "✓ STEP 8: COMPLETE METADATA"
echo "  Back in App Store Connect:"
echo "  [ ] Version number: 1.0"
echo "  [ ] Build: Select the build you just uploaded"
echo "  [ ] Screenshots: Add all screenshots"
echo "  [ ] App Preview Video: (Optional)"
echo "  [ ] Description filled in"
echo "  [ ] Keywords filled in"
echo "  [ ] Support URL filled in"
echo "  [ ] Privacy Policy URL filled in"
echo ""

echo "✓ STEP 9: RATING"
echo "  [ ] Complete Content Rating Questionnaire"
echo "     (Usually all 'None' for PCS Express)"
echo ""

echo "✓ STEP 10: SUBMIT FOR REVIEW"
echo "  1. In App Store Connect, your app version"
echo "  2. Scroll to bottom"
echo "  3. Click 'Submit for Review' (blue button)"
echo "  [ ] Submission sent"
echo ""

echo "✓ STEP 11: WAIT FOR REVIEW"
echo "  [ ] Monitor status in App Store Connect"
echo "     Timeline: 24 hours - 5 days (usually 1-2 days)"
echo "  [ ] Check email for approval or rejection"
echo ""

echo "✓ STEP 12: LAUNCH!"
echo "  [ ] App approved!"
echo "  [ ] Your PCS Express app is now on the App Store"
echo "  [ ] Share with service members!"
echo ""

echo "==============================================="
echo "📱 Your app is ready to submit!"
echo ""
echo "Questions? See IOS_APPSTORE_GUIDE.md for details"
