/*
 * Interactive demo tour for PCS Express.
 *
 * Walks the user (running on the demo profile — Marcus Thompson, Army
 * National Guard, Fort Liberty → USAG Humphreys, OCONUS, PPM move with
 * pets and dependents) through the redesigned feature set. Each step
 * highlights one feature, gives a one-line orientation, and lists the
 * concrete details a user should look at on that screen.
 *
 * Steps are tab-aware: clicking the action button switches to the
 * relevant tab so the user can see the live UI while reading the
 * description. "Highlight" identifies which bottom-nav category the step
 * relates to so future versions can ring-light it.
 */

import { useState } from 'react';
import './DemoTour.css';

const DEMO_STEPS = [
  {
    id: 'welcome',
    title: 'Welcome to PCS Express',
    description: "You're now in interactive demo mode as SFC Marcus Thompson — Army National Guard, Fort Liberty → USAG Humphreys, OCONUS PCS in 75 days with spouse, 3 children, pets, and a Personally Procured (PPM) move.",
    content: 'This tour walks you through the redesigned 3-step onboarding, the Zero-Upload promise, the T-Minus dashboard, branch-aware terminology, component-specific guidance (Title 10 / Title 32 for Guard), and the full PCS Checklist + Documents workflow.\n\nClick Next to begin. You can Skip at any time.',
    action: null,
  },
  {
    id: 'home-tminus',
    title: 'T-Minus Dashboard',
    description: 'The Home tab opens on the T-Minus countdown derived from your Report-NLT date.',
    content: 'For this demo (Report-NLT in 75 days):\n• T-90 — Schedule HHG pickup / file DPS application (already passed)\n• T-75 — Request house-hunting leave (PTDY) if entitled (today)\n• T-60 — Pull medical / dental records\n• T-45 — School records, EFMP screening confirmed\n\nThe banner color reflects urgency: green (post-report) → accent (>30d) → amber (≤30d) → red (≤7d).',
    action: 'Go to Home',
    target: 'home',
  },
  {
    id: 'home-component',
    title: 'Component-Aware Guidance',
    description: 'Marcus is in the National Guard, so the Home tab surfaces a Title 10 / Title 32 callout the Active-Duty UI doesn\'t show.',
    content: 'Scroll down on the Home tab. The "National Guard Notes" card covers:\n• Confirming whether orders cite Title 10 (federal) or Title 32 (state with federal pay)\n• Notifying your State JFHQ J1 / SAD office before departure\n• State retention roster vs. detach-to-federal-service\n• TRICARE Reserve Select → Prime enrollment within 60 days\n• Cross-state license, tax residency, voter registration for 6+ month assignments',
    action: 'Go to Home',
    target: 'home',
  },
  {
    id: 'zero-upload',
    title: '🔒 Zero-Upload Privacy Promise — AES-256',
    description: "Why we never ask you to upload documents.",
    content: 'PCS Express never stores your orders, IDs, or any other files. Everything you type stays on your device, encrypted with AES-256-GCM via the Web Crypto API.\n\n• Key: 256-bit AES-GCM, generated by the browser, persisted as a non-extractable CryptoKey in IndexedDB. The raw key bytes never reach JavaScript.\n• Storage: every value written to localStorage is an envelope { v: 1, alg: \'AES-256-GCM\', iv, data }. The plaintext never touches disk.\n• No server: there is no PCS Express backend that sees your data — we have nothing to leak.\n\nOpen your browser DevTools → Application → Local Storage to verify: every value is ciphertext, not your name or installation.',
    action: null,
    target: 'home',
  },
  {
    id: 'translation',
    title: '🌍 12-Language Translation Runtime',
    description: 'Pick any language during onboarding and the whole app shifts.',
    content: 'Supported: English, Español, Deutsch, Français, 한국어, 日本語, Tagalog, العربية, 中文, Italiano, Português, Tiếng Việt.\n\n• Navigation, headings, and explicit labels are translated through a per-language dictionary (the ot()/trFrom helper).\n• Longer content uses a topic-localized runtime fallback — Specific wording may generalize. The Home tab banner reminds non-English users to consult the English original or official source before acting.\n• Re-onboard from More → Reset to switch languages; the picker shows every supported language in its native script.',
    action: null,
    target: 'home',
  },
  {
    id: 'documents',
    title: '📋 PCS Documents — Branch-Tailored',
    description: 'Every form in your branch\'s checklist has a corresponding gather-and-check item in Documents, sorted into 7 tabs.',
    content: 'For Marcus (Army National Guard, OCONUS):\n• Unit (Orders): DA 31 Leave, SRB / IPPS-A snapshot, DA 4187\n• Family & Admin: DD 93 Emergency Data, SGLV 8286 SGLI Beneficiary, DA 5305 Family Care Plan, DA 5960 BAH, DA 7695 EFMP\n• OCONUS: DD 1056 No-Fee Passport Authorization, Official + dependent passports, SOFA documentation, Country Clearance\n• Household Goods: HHG counseling + DPS application, weight tickets, inventory & damage report, POV shipment\n• Travel & Finance: DD 1351-2 voucher, DD 2560 advance/DLA, lodging + mileage receipts\n• Housing: BAH lookup, lease termination (SCRA)\n• Medical: SF 600/603 transfer, immunizations, TRICARE switch\n\nEach card has a checkbox — no upload, just mark-as-gathered.',
    action: 'Go to Documents',
    target: 'documents',
  },
  {
    id: 'checklist',
    title: '✓ PCS Checklist — 102 Tasks Across 6 Phases',
    description: 'The checklist is branch-specific and runs from Orders Received through In-Processing.',
    content: 'For Army users, 102 phased tasks across:\n• Orders Received (13 tasks)\n• 90 Days Out (17 tasks) — TMO appointment, DPS counseling, BAH lookup, EFMP enrollment\n• 60 Days Out (18 tasks) — medical/dental records, SGLI update, OMPF print, OCONUS overseas screening\n• 30 Days Out (17 tasks) — confirm pack-out, TLE lodging, out-process ACS/Transport/Finance\n• Move Week (15 tasks) — pack-out witnessing, HHG inventory, hand-carry list, TRICARE switch\n• In-Processing (22 tasks) — report, DD 1351-2 voucher, DEERS, MTF enrollment, brief gaining commander\n\nNavy, Marine Corps, Air Force, Space Force, and Coast Guard each have parallel 100+ task checklists with branch-native terminology (NSIPS, MOL, myPers, Direct Access).',
    action: 'Go to Checklist',
    target: 'checklist',
  },
  {
    id: 'home-relocation',
    title: '🏠 Home Relocation Calculators',
    description: 'BAH, OHA, PPM/DITY incentive estimator, and Move Budget Tracker in one tab.',
    content: 'For Marcus heading OCONUS:\n• OHA Calculator: rate by duty country, pay grade, and family size (BAH does not apply OCONUS)\n• PPM Calculator: estimated incentive payment based on government-arranged HHG cost vs. your actual move cost — Marcus picked PPM at onboarding, so this is the relevant calculator\n• Move Budget Tracker: side-by-side comparison of entitlement estimates vs. actual spending — helps avoid the ~$5,000 average unreimbursed loss per move\n• Duty Station Directory: housing wait times, TRICARE MTF, school districts, and base office numbers for 139 installations',
    action: 'Go to Home Relocation',
    target: 'home-relocation',
  },
  {
    id: 'base-intel',
    title: '🎖️ Base Intelligence',
    description: 'Community reviews from verified service members for the gaining installation.',
    content: 'For USAG Humphreys you\'ll see:\n• Verified reviews tagged "Military Family Verified" or "Community review"\n• Honest empty-state UX when no reviews exist for an installation (we never auto-generate fake reviews)\n• Categories: Housing, Schools, Childcare\n• Source diligence: reviews are paraphrased from public community channels and reviewed before inclusion; no PII or scraped content is stored.',
    action: 'Go to Base Intelligence',
    target: 'base-intelligence',
  },
  {
    id: 'family-readiness',
    title: '👨‍👩‍👧 Family Readiness',
    description: 'Sub-tabs for Deployment, EFMP, Employment, Permanent Resident, Pets, and Schools.',
    content: 'Marcus has Pets toggled on, so the Pets sub-tab is especially relevant:\n• APHIS / USDA pet-import certificate workflow for OCONUS\n• Veterinary checklist (rabies, microchip, broad-spectrum vaccinations)\n• Host-nation quarantine rules (Korea is rabies-controlled — typically no quarantine for compliant pets)\n• Carrier reservations and temperature embargo dates\n\nThe Employment sub-tab includes MyCAA / SECO resources for spouse employment continuity.',
    action: 'Go to Family Readiness',
    target: 'family',
  },
  {
    id: 'finish',
    title: '✨ Tour Complete',
    description: 'You have walked through the full PCS Express feature set on the demo profile.',
    content: "Ready to set up your own profile?\n\n1. Close this tour\n2. Tap Reset / Re-onboard in More menu\n3. Enter your real branch, component, installations, and Report-NLT date\n4. Your data is encrypted with AES-256-GCM and stored only on this device\n\nIf you ever spot UI text that still appears in English when a different language is selected, the in-app banner explains the translation scope — long instructional content may generalize.\n\nWelcome aboard.",
    action: 'Close Demo',
    target: null,
  },
];

export function DemoTour({ onTabChange, onClose }) {
  const [currentStep, setCurrentStep] = useState(0);
  const step = DEMO_STEPS[currentStep];

  const handleNext = () => {
    if (currentStep < DEMO_STEPS.length - 1) setCurrentStep(currentStep + 1);
    else onClose();
  };
  const handlePrev = () => {
    if (currentStep > 0) setCurrentStep(currentStep - 1);
  };
  const handleAction = () => {
    if (step.action === 'Close Demo') { onClose(); return; }
    if (step.target && onTabChange) onTabChange(step.target);
  };

  const progress = ((currentStep + 1) / DEMO_STEPS.length) * 100;

  return (
    <div className="demo-overlay" data-no-language-runtime>
      <div className="demo-modal">
        <div className="demo-header">
          <h2>{step.title}</h2>
          <button className="demo-close" onClick={onClose} aria-label="Close demo tour">✕</button>
        </div>

        <div className="demo-content">
          <p className="demo-description">{step.description}</p>
          <pre className="demo-text">{step.content}</pre>
        </div>

        <div className="demo-footer">
          <div className="demo-progress">
            <div className="progress-bar">
              <div className="progress-fill" style={{ width: `${progress}%` }} />
            </div>
            <span className="progress-text">{currentStep + 1} / {DEMO_STEPS.length}</span>
          </div>

          <div className="demo-buttons">
            <button onClick={handlePrev} disabled={currentStep === 0} className="btn-secondary">← Back</button>
            {step.action && <button onClick={handleAction} className="btn-primary">{step.action}</button>}
            <button onClick={handleNext} className="btn-primary">
              {currentStep === DEMO_STEPS.length - 1 ? 'Finish' : 'Next →'}
            </button>
          </div>

          <button onClick={onClose} className="btn-skip">Skip Tour</button>
        </div>
      </div>
    </div>
  );
}

export default DemoTour;
